# Generated by Django 4.2.16 on 2024-10-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='test_cases',
            field=models.TextField(help_text='Define test cases as Python code'),
        ),
    ]
