# Generated by Django 5.1.1 on 2024-10-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C')], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='test_cases',
            field=models.TextField(help_text='Define test cases as Python/Java/C code'),
        ),
    ]
