# Generated by Django 5.1.1 on 2024-10-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_exercise_language_alter_exercise_test_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("java", "Java"),
                    ("c", "C"),
                    ("mysql", "MySql"),
                ],
                default="python",
                max_length=10,
            ),
        ),
    ]
